### ISSUE TITLE
Maven build Error: error: annotations are not supported in -source 1.3

### ISSUE THREAD

**Issue by labsji** [camunda/camunda-get-started-spring-boot#1]
I cloned the repo with:
git clone https://github.com/camunda/camunda-get-started-spring-boot.git
And did
git checkout Step-1
When I try to build using mvn clean install
I get this error:
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 13.288s
[INFO] Finished at: Fri Oct 27 13:54:52 IST 2017
[INFO] Final Memory: 18M/129M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:2.0.2:compile (default-compile) on project loan-approval-spring-boot: Compilation failure: Compilation failure:
[ERROR] /home/balaji/Camunda/camunda-get-started-spring-boot/src/main/java/org/camunda/bpm/getstarted/loanapproval/WebappExampleProcessApplication.java:[6,1] error: annotations are not supported in -source 1.3
[ERROR] 
[ERROR] (use -source 5 or higher to enable annotations)

```
Most likely it is a  maven-compiler-plugin version config issue.

**Comment by sdorokhova** [comment]
@labsji , thank you for pointing out. Can you tell which Maven version are you using? (mvn -version)

**Comment by labsji** [comment]
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.8.0_66, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-8-oracle/jre
Default locale: en_IN, platform encoding: UTF-8
OS name: "linux", version: "3.19.0-31-generic", arch: "amd64", family: "unix"

**Comment by sdorokhova** [comment]
Is there any reason to use this rather old version (over 4 years old)? 
Can you try running `mvn clean install -Dmaven.compiler.source=1.5 -Dmaven.compiler.target=1.5`?

**Comment by labsji** [comment]
Thanks for the upgrade tip. Done.
The command line switch also works just fine.

Thanks.
